/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pltw;

public class App {

    public static void main(String[] args) {
        Student s = new Student("John Doe", 0, 9);
        Student t = new Student("Dohn Joe", 1, 10);
        Student r = new Student("Jane Doe", 0, 11);

        System.out.println(s.equals(t));
        System.out.println(s.equals(r));

        System.out.println(s);
    }
}
